version: '3.8'

services:
  gaja-server:
    build: .
    container_name: gaja-server
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config/server_config.json:/app/config/server_config.json:ro
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - gaja-network

networks:
  gaja-network:
    driver: bridge
